# Generated by Django 5.0.1 on 2024-01-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='mainpage/images'),
        ),
    ]
