# Generated by Django 5.0.1 on 2024-01-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioproject',
            name='credits',
            field=models.CharField(default='Mix', max_length=300),
        ),
    ]
