# Generated by Django 5.0.1 on 2024-01-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_profile', '0002_audioproject_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioproject',
            name='credits',
            field=models.CharField(default='', max_length=300),
        ),
    ]
