# Generated by Django 5.0.1 on 2024-01-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_profile', '0003_alter_audioproject_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGameProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='audio_profile/images')),
                ('url', models.URLField(blank=True)),
                ('credits', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
